from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any, Union
from enum import Enum

class InputMode(str, Enum):
    SINGLE_OPTICAL = "single_optical"
    SINGLE_SAR = "single_sar"
    OPTICAL_SAR_PAIR = "optical_sar_pair"
    BITEMPORAL_PAIR = "bitemporal_pair"

class TaskType(str, Enum):
    VQA = "vqa"
    CAPTIONING = "captioning"
    GROUNDING = "grounding"
    CHANGE_DETECTION = "change_detection"
    CHANGE_DESCRIPTION = "change_description"
    OPTICAL_SAR_FUSION = "optical_sar_fusion"

class CropSuitability(BaseModel):
    crop: str
    score: int = Field(..., ge=0, le=100)
    rationale: str
    condition: str

class AgricultureRequest(BaseModel):
    session_id: str
    location: str = Field(..., min_length=2, max_length=150)
    soil_type: str = Field(..., min_length=2, max_length=50)

class AgricultureResponse(BaseModel):
    location: str
    weather_source: str
    weather_available: bool
    temperature_c: Optional[float] = None
    humidity_percent: Optional[float] = None
    precipitation_mm: Optional[float] = None
    forecast_rainfall_mm: Optional[float] = None
    land_assessment: str
    vegetation_proxy: float
    soil_moisture_proxy: float
    soil_type: str
    crops: List[CropSuitability]
    disclaimer: str

class ExecutionStep(BaseModel):
    step_index: int
    name: str
    description: str
    model_name: str
    execution_time_ms: float
    status: str = "completed"
    metadata: Optional[Dict[str, Any]] = None

class BoundingBox(BaseModel):
    label: str
    box_2d: List[float] = Field(..., description="[ymin, xmin, ymax, xmax] normalized to 0-1000")
    confidence: float
    color: str = "#00F0FF"
    category: Optional[str] = None
    area_hectares: Optional[float] = None

class QuantitativeMetric(BaseModel):
    label: str
    value: Union[str, float, int]
    unit: Optional[str] = ""
    trend: Optional[str] = None # 'up', 'down', 'stable'

class VisualEvidence(BaseModel):
    primary_image_url: str
    secondary_image_url: Optional[str] = None
    overlay_image_url: Optional[str] = None
    diff_mask_url: Optional[str] = None
    fusion_image_url: Optional[str] = None
    bboxes: List[BoundingBox] = []
    spectral_indices: Optional[Dict[str, float]] = None

class ConfidenceBreakdown(BaseModel):
    semantic_alignment: float
    spectral_consistency: float
    spatial_grounding: float
    overall: float

class QueryRequest(BaseModel):
    query: str
    input_mode: InputMode
    session_id: str
    override_task: Optional[TaskType] = None
    confidence_threshold: Optional[float] = 0.5

class QueryResponse(BaseModel):
    answer: str
    detected_task: TaskType
    task_description: str
    selected_model: str
    confidence_score: float
    confidence_breakdown: ConfidenceBreakdown
    execution_trace: List[ExecutionStep]
    visual_evidence: VisualEvidence
    quantitative_metrics: List[QuantitativeMetric]
    disclaimer: str = "Analysis generated by SatQuery AI Remote Sensing Multimodal Agentic Pipeline."

class ImageMeta(BaseModel):
    filename: str
    url: str
    role: str # "optical", "sar", "time1", "time2", "primary"
    width: int
    height: int
    format: str
    channels: int
    estimated_gsd_meters: float
    sensor_type: str

class UploadResponse(BaseModel):
    session_id: str
    input_mode: InputMode
    images: List[ImageMeta]
    validation_status: str
    validation_message: str

class SampleDatasetItem(BaseModel):
    id: str
    title: str
    description: str
    category: str
    input_mode: InputMode
    location: str
    acquisition_dates: List[str]
    images: List[Dict[str, str]]
    recommended_queries: List[str]
    sensor_details: str
    taxonomies: List[str]

class ReportRequest(BaseModel):
    session_id: str
    query: str
    answer: str
    detected_task: str
    selected_model: str
    confidence_score: float
    execution_trace: List[Dict[str, Any]]
    quantitative_metrics: List[Dict[str, Any]]
    image_urls: Dict[str, str]
